# Generated by Django 5.0 on 2023-12-14 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Polls',
            new_name='CategoryModel',
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='PollsModel',
        ),
    ]
